export const articles = [
  {
    category: "Technology",
    title: "Generative AI: The New Creative Partner",
    slug: "generative-ai-new-creative-partner",
    excerpt:
      "How artists and writers are using large language models to augment their creative process without losing their voice.",
    author: "Marcus Thorne",
    readTime: "10 min read",
    views: 42500,
    likes: 12100,
  },
  {
    category: "Design",
    title: "Craftsmanship in the Age of Scale",
    slug: "craftsmanship-in-the-age-of-scale",
    excerpt:
      "Why physical objects and mechanical precision still matter in an increasingly ethereal, cloud-based world.",
    author: "David Sterling",
    readTime: "6 min read",
    views: 28000,
    likes: 8400,
  },
  {
    category: "Lifestyle",
    title: "The Future of Gastronomy",
    slug: "future-of-gastronomy",
    excerpt:
      "Sustainable practices and molecular techniques that are redefining what it means to dine in the 21st century.",
    author: "Helena Blake",
    readTime: "8 min read",
    views: 19000,
    likes: 6200,
  },
  {
    category: "Design",
    title: "Urban Paradigms: Building for Community",
    slug: "urban-paradigms-building-for-community",
    excerpt:
      "How architecture is evolving to foster human connection in the world's most densely populated cities.",
    author: "Arthur Wright",
    readTime: "12 min read",
    views: 15000,
    likes: 4500,
  },
  {
    category: "Technology",
    title: "Quantum Computing: A Decadal Forecast",
    slug: "quantum-computing-decadal-forecast",
    excerpt:
      "Understanding the roadmap to quantum advantage and what it means for cryptography, medicine, and climate modeling.",
    author: "Dr. Elena Vance",
    readTime: "15 min read",
    views: 14200,
    likes: 3900,
  },
  {
    category: "Philosophy",
    title: "Deep Work: Why Silence is the Ultimate Luxury",
    slug: "deep-work-silence-ultimate-luxury",
    excerpt:
      "Rediscovering the power of focused attention in an age of constant digital distraction and notification overload.",
    author: "Sarah Jenkins",
    readTime: "7 min read",
    views: 11000,
    likes: 3200,
  },
  {
    category: "Architecture",
    title: "The Silent Revolution: How Generative Design is Reshaping Our Cities",
    slug: "silent-revolution-generative-design",
    excerpt:
      "Architecture has always been a conversation between the human imagination and the physical constraints of our world.",
    author: "Elena Thorne",
    readTime: "12 min read",
    views: 9800,
    likes: 2800,
  },
  {
    category: "Science",
    title: "Reimagining Productivity: Beyond the To-Do List",
    slug: "reimagining-productivity-beyond-todo",
    excerpt:
      "Why the most effective systems are the ones that adapt to your cognitive rhythms.",
    author: "Marcus Thorne",
    readTime: "6 min read",
    views: 8400,
    likes: 2100,
  },
];

export const categories = [
  {
    name: "AI & Machine Learning",
    slug: "ai-machine-learning",
    description: "Understanding the algorithms shaping our tomorrow.",
    postCount: 124,
    featured: true,
    icon: "psychology",
  },
  {
    name: "Design Systems",
    slug: "design-systems",
    description: "The principles and patterns behind great interfaces.",
    postCount: 86,
    featured: false,
    icon: "architecture",
  },
  {
    name: "Technology",
    slug: "technology",
    description: "The hardware and software revolution.",
    postCount: 92,
    featured: false,
    icon: "terminal",
  },
  {
    name: "Modern Lifestyle",
    slug: "modern-lifestyle",
    description: "Living with intention in a digital age.",
    postCount: 64,
    featured: false,
    icon: "self_improvement",
  },
  {
    name: "Global Economy",
    slug: "global-economy",
    description: "Data-driven insights into world markets.",
    postCount: 42,
    featured: false,
    icon: "trending_up",
  },
  {
    name: "Philosophy & Ethics",
    slug: "philosophy-ethics",
    description: "Navigating the moral landscape of the 21st century.",
    postCount: 31,
    featured: false,
    icon: "account_balance",
  },
  {
    name: "Future of Work",
    slug: "future-of-work",
    description: "Remote trends, automation, and the modern career.",
    postCount: 55,
    featured: false,
    icon: "work",
  },
];

export const trendingArticles = [
  {
    rank: 1,
    title: "The Invisible Architect: How AI Reshapes Human Agency",
    slug: "invisible-architect-ai-reshapes-agency",
    excerpt:
      "An exploration of the subtle ways generative models are beginning to influence our daily decision-making processes and the ethical frameworks we must build today.",
    category: "Tech Ethics",
    author: "Dr. Elena Vance",
    readTime: "8 min read",
    views: 42500,
    likes: 12100,
  },
  {
    rank: 2,
    title: "Sustainable Design in a Circular Economy",
    slug: "sustainable-design-circular-economy",
    excerpt:
      "Why longevity is becoming the most disruptive feature in modern product development.",
    category: "Architecture",
    readTime: "4 min read",
    views: 28000,
    likes: 7400,
  },
  {
    rank: 3,
    title: "The Psychology of Deep Work",
    slug: "psychology-of-deep-work",
    excerpt:
      "Understanding the neurological pathways that enable peak cognitive performance.",
    category: "Mental Health",
    readTime: "12 min read",
    views: 19000,
    likes: 5600,
  },
  {
    rank: 4,
    title: "Reimagining Productivity: Beyond the To-Do List",
    slug: "reimagining-productivity-beyond-todo",
    category: "Productivity",
    views: 15000,
    readTime: "6 min",
  },
  {
    rank: 5,
    title: "Quantum Computing: A Decadal Forecast",
    slug: "quantum-computing-decadal-forecast",
    category: "Technology",
    views: 14200,
    readTime: "15 min",
  },
  {
    rank: 6,
    title: "Gastronomy & Brain Health: The Gut-Mind Connection",
    slug: "gastronomy-brain-health-gut-mind",
    category: "Health",
    views: 11000,
    readTime: "7 min",
  },
  {
    rank: 7,
    title: "Why Print Media is Making a Luxury Comeback",
    slug: "print-media-luxury-comeback",
    category: "Media",
    views: 9800,
    readTime: "9 min",
  },
];
